
package nl.gpesoft.javaee.service.adapter.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2.10
 * 
 */
@XmlRootElement(name = "DeveloperMustBeAnAdultException", namespace = "http://adapter.service.javaee.gpesoft.nl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeveloperMustBeAnAdultException", namespace = "http://adapter.service.javaee.gpesoft.nl/")
public class DeveloperMustBeAnAdultExceptionBean {

    private String message;

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
